import { CurrencyOption } from '../types';

export const WORLD_CURRENCIES: CurrencyOption[] = [
  {
    code: 'BDT',
    symbol: '৳',
    nameBn: 'বাংলাদেশী টাকা',
    nameEn: 'Bangladeshi Taka',
    flag: '🇧🇩',
  },
  {
    code: 'USD',
    symbol: '$',
    nameBn: 'মার্কিন ডলার',
    nameEn: 'US Dollar',
    flag: '🇺🇸',
  },
  {
    code: 'EUR',
    symbol: '€',
    nameBn: 'ইউরো',
    nameEn: 'Euro',
    flag: '🇪🇺',
  },
  {
    code: 'GBP',
    symbol: '£',
    nameBn: 'ব্রিটিশ পাউন্ড',
    nameEn: 'British Pound',
    flag: '🇬🇧',
  },
  {
    code: 'SAR',
    symbol: '﷼',
    nameBn: 'সৌদি রিয়াল',
    nameEn: 'Saudi Riyal',
    flag: '🇸🇦',
  },
  {
    code: 'AED',
    symbol: 'د.إ',
    nameBn: 'ইউএই দিরহাম',
    nameEn: 'UAE Dirham',
    flag: '🇦🇪',
  },
  {
    code: 'INR',
    symbol: '₹',
    nameBn: 'ভারতীয় রুপি',
    nameEn: 'Indian Rupee',
    flag: '🇮🇳',
  },
  {
    code: 'MYR',
    symbol: 'RM',
    nameBn: 'মালয়েশিয়ান রিঙ্গিত',
    nameEn: 'Malaysian Ringgit',
    flag: '🇲🇾',
  },
  {
    code: 'KWD',
    symbol: 'د.ك',
    nameBn: 'কুয়েতি দিনার',
    nameEn: 'Kuwaiti Dinar',
    flag: '🇰🇼',
  },
  {
    code: 'QAR',
    symbol: '﷼',
    nameBn: 'কাতারি রিয়াল',
    nameEn: 'Qatari Riyal',
    flag: '🇶🇦',
  },
  {
    code: 'OMR',
    symbol: 'ر.ع.',
    nameBn: 'ওমানি রিয়াল',
    nameEn: 'Omani Rial',
    flag: '🇴🇲',
  },
  {
    code: 'BHD',
    symbol: 'د.ب',
    nameBn: 'বাহরাইনি দিনার',
    nameEn: 'Bahraini Dinar',
    flag: '🇧🇭',
  },
  {
    code: 'SGD',
    symbol: 'S$',
    nameBn: 'সিঙ্গাপুর ডলার',
    nameEn: 'Singapore Dollar',
    flag: '🇸🇬',
  },
  {
    code: 'CAD',
    symbol: 'C$',
    nameBn: 'কানাডিয়ান ডলার',
    nameEn: 'Canadian Dollar',
    flag: '🇨🇦',
  },
  {
    code: 'AUD',
    symbol: 'A$',
    nameBn: 'অস্ট্রেলিয়ান ডলার',
    nameEn: 'Australian Dollar',
    flag: '🇦🇺',
  },
  {
    code: 'JPY',
    symbol: '¥',
    nameBn: 'জাপানি ইয়েন',
    nameEn: 'Japanese Yen',
    flag: '🇯🇵',
  },
  {
    code: 'CNY',
    symbol: '¥',
    nameBn: 'চাইনিজ ইউয়ান',
    nameEn: 'Chinese Yuan',
    flag: '🇨🇳',
  },
  {
    code: 'TRY',
    symbol: '₺',
    nameBn: 'তুর্কি লিরা',
    nameEn: 'Turkish Lira',
    flag: '🇹🇷',
  },
  {
    code: 'PKR',
    symbol: '₨',
    nameBn: 'পাকিস্তানি রুপি',
    nameEn: 'Pakistani Rupee',
    flag: '🇵🇰',
  },
  {
    code: 'THB',
    symbol: '฿',
    nameBn: 'থাই বাথ',
    nameEn: 'Thai Baht',
    flag: '🇹🇭',
  },
  {
    code: 'CHF',
    symbol: 'Fr',
    nameBn: 'সুইস ফ্রাঁ',
    nameEn: 'Swiss Franc',
    flag: '🇨🇭',
  },
  {
    code: 'SEK',
    symbol: 'kr',
    nameBn: 'সুইডিশ ক্রোনা',
    nameEn: 'Swedish Krona',
    flag: '🇸🇪',
  },
  {
    code: 'NOK',
    symbol: 'kr',
    nameBn: 'নরওয়েজিয়ান ক্রোন',
    nameEn: 'Norwegian Krone',
    flag: '🇳🇴',
  },
  {
    code: 'DKK',
    symbol: 'kr',
    nameBn: 'ড্যানিশ ক্রোন',
    nameEn: 'Danish Krone',
    flag: '🇩🇰',
  },
  {
    code: 'ZAR',
    symbol: 'R',
    nameBn: 'দক্ষিণ আফ্রিকান র্যান্ড',
    nameEn: 'South African Rand',
    flag: '🇿🇦',
  },
  {
    code: 'BRL',
    symbol: 'R$',
    nameBn: 'ব্রাজিলিয়ান রিয়াল',
    nameEn: 'Brazilian Real',
    flag: '🇧🇷',
  },
  {
    code: 'RUB',
    symbol: '₽',
    nameBn: 'রাশিয়ান রুবল',
    nameEn: 'Russian Ruble',
    flag: '🇷🇺',
  },
  {
    code: 'KRW',
    symbol: '₩',
    nameBn: 'দক্ষিণ কোরিয়ান ওন',
    nameEn: 'South Korean Won',
    flag: '🇰🇷',
  },
  {
    code: 'IDR',
    symbol: 'Rp',
    nameBn: 'ইন্দোনেশিয়ান রূপিয়া',
    nameEn: 'Indonesian Rupiah',
    flag: '🇮🇩',
  },
  {
    code: 'PHP',
    symbol: '₱',
    nameBn: 'ফিলিপাইন পেসো',
    nameEn: 'Philippine Peso',
    flag: '🇵🇭',
  },
  {
    code: 'VND',
    symbol: '₫',
    nameBn: 'ভিয়েতনামিজ ডং',
    nameEn: 'Vietnamese Dong',
    flag: '🇻🇳',
  },
  {
    code: 'EGP',
    symbol: 'E£',
    nameBn: 'মিশরীয় পাউন্ড',
    nameEn: 'Egyptian Pound',
    flag: '🇪🇬',
  },
  {
    code: 'NZD',
    symbol: 'NZ$',
    nameBn: 'নিউজিল্যান্ড ডলার',
    nameEn: 'New Zealand Dollar',
    flag: '🇳🇿',
  },
  {
    code: 'NGN',
    symbol: '₦',
    nameBn: 'নাইজেরিয়ান নায়রা',
    nameEn: 'Nigerian Naira',
    flag: '🇳🇬',
  },
];
